Section "ServerFlags"
	Option "AutoAddGPU" "false"
EndSection

Section "Device"
	Identifier  "LCD Panel"
	Driver      "fbdev"
	Option      "fbdev" "/dev/fb1"
EndSection

Section "Screen"
	Identifier "LCD Screen"
	Device     "LCD Panel"
	DefaultDepth 24
	SubSection "Display"
		Depth 24
		Modes "1440x960"
	EndSubSection
EndSection
