Section "ServerLayout"
    Identifier "LCD"
    Screen 0 "HDMI Screen"
    Screen 1 "LCD Screen" RightOf "HDMI Screen"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "HDMI Panel"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "none"
EndSection

Section "Device"
    Identifier "LCD Panel"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card1"
    Option "AccelMethod" "none"
EndSection

Section "Monitor"
    Identifier "HDMI Monitor"
EndSection

Section "Monitor"
    Identifier "LCD Monitor"
    DisplaySize 406 271
EndSection

Section "Screen"
    Identifier "HDMI Screen"
    Device "HDMI Panel"
    Monitor "HDMI Monitor"
    DefaultDepth 24
EndSection

Section "Screen"
    Identifier "LCD Screen"
    Device "LCD Panel"
    Monitor "LCD Monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "480x320"
    EndSubSection
EndSection
