Section "ServerLayout"
    Identifier "LCD"
    Screen 0 "HDMI Screen"
    Option "AutoAddGPU" "false"
EndSection

Section "Device"
    Identifier "HDMI Panel"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card0"
    Option "AccelMethod" "none"
EndSection

Section "Monitor"
    Identifier "HDMI Monitor"
EndSection

Section "Screen"
    Identifier "HDMI Screen"
    Device "HDMI Panel"
    Monitor "HDMI Monitor"
    DefaultDepth 24
EndSection
